# Generated by Django 6.0.7 on 2026-07-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AddField(
            model_name='post',
            name='title_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
