"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
"""
Django settings for the project.
This file contains the main configuration for your Django application.
"""

from pathlib import Path

# The main project folder (used to build file paths)
BASE_DIR = Path(__file__).resolve().parent.parent


# =========================
# Security Settings
# =========================

# Secret key used by Django for security (keep it private in production)
SECRET_KEY = 'django-insecure-vjg##f&sgdhg6z6x%4kv3q#gk+w&q6)=ofwsl+dtei7a#yi%%g'

# Shows detailed error pages when True (only for development)
DEBUG = True

# List of domains that are allowed to access the project
ALLOWED_HOSTS = []


# =========================
# Installed Applications
# =========================

# Apps that are available in this Django project
INSTALLED_APPS = [
    'django.contrib.admin',         # Django admin dashboard
    'django.contrib.auth',          # User authentication system
    'django.contrib.contenttypes',  # Content type framework
    'django.contrib.sessions',      # Session management
    'django.contrib.messages',      # Flash messages (success, error, etc.)
    'django.contrib.staticfiles',   # Static files (CSS, JS, Images)

    'blog',                         # Our custom blog app
]


# =========================
# Middleware
# =========================

# Middleware processes every request and response
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',          # Security features
    'django.contrib.sessions.middleware.SessionMiddleware',   # Handles user sessions
    'django.middleware.common.CommonMiddleware',              # Common request/response features
    'django.middleware.csrf.CsrfViewMiddleware',              # Protects against CSRF attacks
    'django.contrib.auth.middleware.AuthenticationMiddleware',# Handles logged-in users
    'django.contrib.messages.middleware.MessageMiddleware',   # Enables messages
    'django.middleware.clickjacking.XFrameOptionsMiddleware', # Protects against clickjacking
]


# Main URL configuration file
ROOT_URLCONF = 'config.urls'


# =========================
# Templates
# =========================

# Configuration for HTML templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        # Extra template folders (empty for now)
        'DIRS': [],

        # Automatically looks for templates inside each app
        'APP_DIRS': True,

        'OPTIONS': {
            # Makes useful variables available inside templates
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# Used when deploying the project
WSGI_APPLICATION = 'config.wsgi.application'


# =========================
# Database
# =========================

# Database configuration (SQLite by default)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',   # Database type
        'NAME': BASE_DIR / 'db.sqlite3',          # Database file location
    }
}


# =========================
# Password Validation
# =========================

# Rules used to validate user passwords
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# =========================
# Language & Time
# =========================

# Default language of the project
LANGUAGE_CODE = 'en-us'

# Default time zone
TIME_ZONE = 'UTC'

# Enable Django's internationalization features
USE_I18N = True

# Store dates and times with time zone support
USE_TZ = True


# =========================
# Static Files
# =========================

# URL used to serve CSS, JavaScript, and images
STATIC_URL = 'static/'